name: Purge GitHub's CDN cache

on:
  workflow_dispatch:
  schedule:
      # restart job asap (minimum every 5 minutes) after it dies
      # as of writing, the default timeout is 6 hours, while means
      # 99.72% uptime
    - cron: '* * * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Purge image until we get time out
        run: |
          URL=$(curl -s https://github.com/malcolmseyd/malcolmseyd/blob/main/README.md | grep -o '[^"]*camo[^"]*' | uniq)
          while true; do
            curl -w "\n" -s -X PURGE $URL;
            sleep 1;
          done
