name: Purge GitHub's CDN cache

on:
  workflow_dispatch:
  schedule:
      # restart job 1 minute after it dies (can't do sooner)
      # as of writing, the default timeout is 6 hours, while means
      # 99.72% uptime
    - cron: '* * * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Purge image until we get time out 
        run: |
          URL=$(curl https://github.com/malcolmseyd/malcolmseyd/blob/main/README.md 2>/dev/null | grep -o '[^"]*camo[^"]*' | uniq)
          COUNT=3600 # 1 hour @ about 1 per second
          for i in $(seq $COUNT); do
            echo "making request $i/$COUNT";
            curl -w "\n" -s -X PURGE $URL;
            sleep 1;
          done | ts '[%Y-%m-%d %H:%M:%.S]'
