name: Purge GitHub's CDN cache

on:
  workflow_dispatch:
  schedule:
      # start jobs as quickly as possible 
      # usually this ends up being about 15 mins, although i have no control

    - cron: '* * * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Purge image until we get time out
        run: |
          URL=$(curl -s https://github.com/malcolmseyd/malcolmseyd/blob/main/README.md | grep -o 'alt="cat".*[^"]*camo[^"]*"' | grep -o '[^"]*camo[^"]*')

          # 3 hours @ about 1 per second
          # workers timeout is 6hrs so this should be plenty
          COUNT=$((60*60*3))
          for i in $(seq $COUNT); do
            echo "making request $i/$COUNT";
            curl -w "\n" -s -X PURGE $URL || true;
            sleep 1;
          done
